version: '3.8'
services:
  mysqldb:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=winpeak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  node-web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
    ports:
      - "5000:5000"
      
volumes:
  my_data: